name: build-dev
on:
  push:
    branches:
      - main
      - v2

jobs:
  build-and-release:
    name: Build and release skupper-console (Dev)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Set up Node.js âš™ï¸
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          cache-path: ~/.cache/yarn

      - name: Set env ğŸ“‹
        run: echo "RELEASE_VERSION=dev-build" >> $GITHUB_ENV

      - name: Install ğŸ“¦
        run: |
          yarn install --frozen-lockfile

      - name: Build ğŸš§
        run: |
          yarn build --mode development
        env:
          CI: false

      - name: Package ğŸ“¦
        run: |
          cd build/ && tar -zcvf ../console-dev.tgz --exclude='./data' .

      - name: Create Release âœ…
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "dev-build"  # Using a proper tag name here
          release_name: "Dev build"
          body: |
            Skupper-console (Dev) build is available as a tar ball:
            - console-dev.tgz
            Issues fixed in this release
            - https://github.com/skupperproject/skupper-console/issues?q=is:issue+milestone:dev
          draft: false  # Set to `false` to make the release public

      - name: Upload Release Asset â¬†ï¸
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./console-dev.tgz
          asset_name: console-dev.tgz
          asset_content_type: application/tar+gzip
